M48
; DRILL file {KiCad 7.0.10} date Tue Apr 30 16:54:11 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-30T16:54:11+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X0.0Y0.0
X0.0Y-4.8819
T2
X0.565Y-3.0418
X0.565Y-3.4918
M30
