M48
; DRILL file {KiCad 7.0.10} date Tue Apr 30 16:31:27 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-30T16:31:27+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X3.968Y-3.19
X3.97Y-4.7265
X7.905Y-3.19
X7.907Y-4.7265
T2
X5.1109Y-4.897
X5.5609Y-4.897
M30
